# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mars_rover.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 30, 721, 571))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.graphGridView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphGridView.setGeometry(QtCore.QRect(10, 10, 701, 551))
        self.graphGridView.setObjectName("graphGridView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 30, 301, 141))
        self.groupBox.setObjectName("groupBox")
        self.spinXGrid = QtWidgets.QSpinBox(self.groupBox)
        self.spinXGrid.setGeometry(QtCore.QRect(109, 40, 51, 30))
        self.spinXGrid.setObjectName("spinXGrid")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 40, 16, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(171, 40, 16, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinYGrid = QtWidgets.QSpinBox(self.groupBox)
        self.spinYGrid.setGeometry(QtCore.QRect(190, 40, 51, 30))
        self.spinYGrid.setObjectName("spinYGrid")
        self.btnUpdateGridSize = QtWidgets.QPushButton(self.groupBox)
        self.btnUpdateGridSize.setGeometry(QtCore.QRect(150, 100, 89, 25))
        self.btnUpdateGridSize.setObjectName("btnUpdateGridSize")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(770, 190, 301, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 101, 17))
        self.label_4.setObjectName("label_4")
        self.btnNumRoversUpdate = QtWidgets.QPushButton(self.groupBox_2)
        self.btnNumRoversUpdate.setGeometry(QtCore.QRect(150, 100, 89, 25))
        self.btnNumRoversUpdate.setObjectName("btnNumRoversUpdate")
        self.spinNumOfRovers = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinNumOfRovers.setGeometry(QtCore.QRect(160, 30, 81, 41))
        self.spinNumOfRovers.setObjectName("spinNumOfRovers")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(770, 360, 301, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.label_5.setObjectName("label_5")
        self.comboRoverSelect = QtWidgets.QComboBox(self.groupBox_3)
        self.comboRoverSelect.setGeometry(QtCore.QRect(60, 44, 221, 31))
        self.comboRoverSelect.setObjectName("comboRoverSelect")
        self.btnMoveForward = QtWidgets.QPushButton(self.groupBox_3)
        self.btnMoveForward.setGeometry(QtCore.QRect(130, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnMoveForward.setFont(font)
        self.btnMoveForward.setObjectName("btnMoveForward")
        self.btnTurnLeft = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTurnLeft.setGeometry(QtCore.QRect(70, 150, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnTurnLeft.setFont(font)
        self.btnTurnLeft.setObjectName("btnTurnLeft")
        self.btnTurnRight = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTurnRight.setGeometry(QtCore.QRect(190, 150, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnTurnRight.setFont(font)
        self.btnTurnRight.setObjectName("btnTurnRight")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 609, 501, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableRoverInfo = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableRoverInfo.setGeometry(QtCore.QRect(0, 20, 501, 131))
        self.tableRoverInfo.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableRoverInfo.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableRoverInfo.setRowCount(0)
        self.tableRoverInfo.setColumnCount(4)
        self.tableRoverInfo.setObjectName("tableRoverInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionOutput_Coordinates = QtWidgets.QAction(MainWindow)
        self.actionOutput_Coordinates.setObjectName("actionOutput_Coordinates")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mars Rover Control System"))
        self.groupBox.setTitle(_translate("MainWindow", "Grid Settings:"))
        self.label.setText(_translate("MainWindow", "Grid Size:"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.btnUpdateGridSize.setText(_translate("MainWindow", "Update"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Rover Settings:"))
        self.label_4.setText(_translate("MainWindow", "No. of Rovers:"))
        self.btnNumRoversUpdate.setText(_translate("MainWindow", "Update"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Navigate Rover:"))
        self.label_5.setText(_translate("MainWindow", "Select:"))
        self.btnMoveForward.setText(_translate("MainWindow", "M"))
        self.btnTurnLeft.setText(_translate("MainWindow", "L"))
        self.btnTurnRight.setText(_translate("MainWindow", "R"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Rover/s Location:"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionOutput_Coordinates.setText(_translate("MainWindow", "Output Coordinates"))

